### ISSUE TITLE
Sortieren der Mitgliederliste: Chinesische Menüoption?

### ISSUE THREAD

**Issue by beo9999** [rpi-virtuell/rw-social-learner#5]
Das ist vermutlich für die meisten User (inkl. mir) nicht verständlich. ;-) 

![20181227_gruppen_mitglieder](https://user-images.githubusercontent.com/12952801/50479850-ecaf2d00-09d8-11e9-8286-23a55e743be8.jpg)

**Comment by staude** [comment]
Das ist die Übersetzung von "Newest Registered" in den Übersetzungen von Boss
https://gruppen.rpi-virtuell.de/wp-admin/admin.php?path=themes%2Fboss%2Flanguages%2Fde_DE.po&bundle=boss&domain=boss&page=loco-theme&action=file-edit
und 
https://gruppen.rpi-virtuell.de/wp-admin/admin.php?path=languages%2Fthemes%2Fboss-de_DE.po&bundle=boss&domain=boss&page=loco-theme&action=file-edit
